### ISSUE TITLE
Crash in rfxcodec_encode_dwt_shift_amd64_sse41

### ISSUE THREAD

**Issue by akireyev** [neutrinolabs/librfxcodec#41] opened 2018-06-26 10:25 UTC
xrdp built from sources at 0.9.6
Reproduces very reliably as follows:

Server:
- sudo su
- ulimit -c unlimited
- /usr/local/bin/xrdp -ns

Client (Windows 10, 1709)
- Connect using LAN settings to an xorgxrdp session. Full-screen 2560x1600
- Open a full-screen terminal (black on white)
- Render a wall of text. E.g. base64 -w 0 < .xsession-errors | less

Observed behavior:
- The session disconnects.
- A core file is generated on the server, in the directory from which xrdp is run. The crash is in loop1p in rfxcodec_encode_dwt_shift_amd64_sse41.

Connections with WAN settings work perfectly.

**Comment by metalefty** [comment] 2018-06-27 05:03
https://github.com/neutrinolabs/xrdp/issues/888 might be identical to this issue.

**Comment by jsorg71** [comment] 2018-06-27 05:12
There is no loop1p, is that correct?

**Comment by akireyev** [comment] 2018-06-27 08:35
@jsorg71, correct, that might be some artifact of memory corruption. Unfortunately, I didn't manage to get gdb to break on this crash, so this is the only thing I have.

@metalefty, it surely looks like one. In my case, the key pieces are the wall of text and RemoteFX codec. I can work for days with RemoteFX (LAN settings) without crashes, but if a terminal in foreground outputs lots of characters, the session crashes immediately. It's no longer possible to reconnect using LAN settings until the wall of text is gone. It is possible to reconnect with WAN settings, get rid of the text, and reconnect with LAN settings again.

**Comment by metalefty** [comment] 2018-06-27 08:47
To break down the issue, can you confirm if it crashes when rfxcodec is built with `--without-simd` option?
It should not use SIMD instructions such as SSE4.1.

**Comment by akireyev** [comment] 2018-06-27 09:06
Instead of building with that option, I modified xrdp_encoder.c to pass RFX_FLAGS_NOACCEL. I still couldn't reconnect, but now the Remote Desktop client was complaining about a protocol error. There was no core dump, so I would assume it didn't crash.

Come think of it, this looks more like memory management problem in the xrdp server itself. It might be interesting to run the entire business under some of the [sanitizers](https://github.com/google/sanitizers).

**Comment by akireyev** [comment] 2018-07-24 16:20
I did a little bit more debugging. There seem to be two problems: one in librfxcodec, the other one on the xup side.

The first problem:
rfx_compose_message_tileset doesn't check if the stream can accept more data, when it's calling rfx_compose_message_tile_yuva. This is most likely causing the crash that I have reported here. A simple check for the buffer_size >= 2000 in rfx_encode_component_rlgr3_amd64_sse41 makes the crash go away. Often, things can recover as the screen contents change to have more empty space, but sometimes RDP client gets stuck and has to be reconnected.

The second problem:
Even though there's a limit on how much compressed data can be produced at once, xrdp_encoder.c assumes that it can fit a single request into max_compressed_bytes. In the wall-of-text case, if num_crects is 1000, this turns out not to be the case. I don't know enough about the protocol to say, if xrdp_encoder could break up the requests itself. If that's not possible, the xup client - such as xorgxrdp - could probably split up its updates to contain fewer crects.

**Comment by johnarnold** [comment] 2018-08-14 19:48
This does sound like the problem I reported on 4k monitors.  FYI, i was able to recover session by temporarily dropping the resolution down to lower resolution (1920x1080), reconnecting, resizing/minimizing the wall-of-text terminal, and then reconnecting at full 4K resolution.

**Comment by ghost** [comment] 2020-04-07 19:32
This is still an issue on 4k screens, and can be reliably reproduced by simply filling up a maximized terminal window.

The segfault described above occurs somewhere in the assembly of rfxcodec_encode_dwt_shift_amd64_sse41.asm, though I suspect the assembly in this file is not the root cause. I initially thought that rfx_encode_message_tile_yuv was passing in some garbage variables, so I recompiled with -O0 in order to see the function arguments that had been optimized out. Unfortunately, when this bug manifests with -O0, gdb is unable to read the core dump. It looks like parts of the stack might be getting clobbered?

I followed the advice above and recompiled with --without-simd. This fixes the segfault issue, because the assembly is not used. But it still causes the RDP session to completely hang when reproducing the bug. If you try to reconnect, you just get a black screen unless you first kill whatever application is writing to a maximized window.

I tried @akireyev’s suggestion above, and patched the rfx_compse_message_tileset function to just return -1 when there wasn’t sufficient space in the stream. However, this results in RDP just hanging, and I get errors from the windows RDP client when trying to reconnect. I know nothing about the RDP protocol specification, so there’s probably some logical error in my attempt at a fix.

**Comment by matt335672** [comment] 2021-12-22 10:59
Duplicate of neutrinolabs/xrdp#2068

**Comment by metalefty** [comment] 2022-09-07 12:44
Let's close duplicates and keep open the most detailed one.

**Closed as completed by metalefty** 2022-09-07 12:44 UTC
Labels: bug
